### ISSUE TITLE
Unknow directives in syscall.s, dlsym.s, tlsdesc.s

### ISSUE THREAD

**Issue by jakirkham** [WebAssembly/musl#50]
Attempted to build this using Clang 6.0.1 built with WebAssembly support, but ran into some issues. IIUC this is still under active development so not too surprised to have a few issues. Also as I'm not too knowledgeable about what is going on here, could certainly be doing something wrong in the build. Tried to include as much relevant info below to reproduce. Any suggestions would be greatly appreciated.

<details>
<summary>Build Log:</summary>

```
$ conda build recipes/wasm32-libc/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for wasm32-libc
INFO:conda_build.metadata:Attempting to finalize metadata for wasm32-libc
Solving environment: ...working... done
BUILD START: ['wasm32-libc-0.0.1a1-0.tar.bz2']
Solving environment: ...working... done

## Package Plan ##

  environment location: /zopt/conda3/conda-bld/wasm32-libc_1534032953302/_build_env


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-1           conda-forge
    ca-certificates: 2018.4.16-0       conda-forge
    clangdev:        6.0.1-default_0   conda-forge
    icu:             58.2-hfc679d8_0   conda-forge
    libcxx:          6.0.1-0           conda-forge
    libffi:          3.2.1-hfc679d8_4  conda-forge
    libiconv:        1.15-h470a237_2   conda-forge
    libxml2:         2.9.8-h422b904_3  conda-forge
    lld:             6.0.1-py36_0      conda-forge
    llvm-meta:       6.0.1-0           conda-forge
    llvmdev:         6.0.1-hf8ce74a_1  conda-forge
    ncurses:         6.1-hfc679d8_1    conda-forge
    openssl:         1.0.2o-h470a237_1 conda-forge
    python:          3.6.6-h5001a0f_0  conda-forge
    readline:        7.0-haf1bffa_1    conda-forge
    sqlite:          3.24.0-h2f33b56_0 conda-forge
    tk:              8.6.8-0           conda-forge
    xz:              5.2.4-h470a237_1  conda-forge
    zlib:            1.2.11-h470a237_3 conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Cloning into '/zopt/conda3/conda-bld/wasm32-libc_1534032953302/work'...
done.
checkout: 'edeb5004e6e016e326c475ce53199755d76d103f'
Note: checking out 'edeb5004e6e016e326c475ce53199755d76d103f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at edeb5004 Merge pull request #49 from jfbastien/fix_size_t
==> git log -n1 <==

fatal: No names found, cannot describe anything.
commit edeb5004e6e016e326c475ce53199755d76d103f
Merge: 0ed10f0b ecef9ab4
Author: Sam Clegg <sbc@chromium.org>
Date:   Wed Jul 25 14:31:43 2018 -0700

    Merge pull request #49 from jfbastien/fix_size_t
    
    Update wasm size_t from int to long to match llvm change

==> git describe --tags --dirty <==

commit edeb5004e6e016e326c475ce53199755d76d103f
Merge: 0ed10f0b ecef9ab4
Author: Sam Clegg <sbc@chromium.org>
Date:   Wed Jul 25 14:31:43 2018 -0700

    Merge pull request #49 from jfbastien/fix_size_t
    
    Update wasm size_t from int to long to match llvm change

==> git status <==

## HEAD (no branch)

source tree in: /zopt/conda3/conda-bld/wasm32-libc_1534032953302/work
checking for C compiler... /zopt/conda3/conda-bld/wasm32-libc_1534032953302/_build_env/bin/clang
checking whether C compiler works... yes
checking whether compiler accepts -Werror=unknown-warning-option... yes
checking whether compiler accepts -Werror=unused-command-line-argument... yes
checking whether compiler accepts -Werror=ignored-optimization-argument... yes
checking whether linker accepts -Werror=unknown-warning-option... yes
checking whether linker accepts -Werror=unused-command-line-argument... yes
checking for C compiler family... clang
checking for toolchain wrapper to build... none
checking target system type... x86_64-apple-darwin15.6.0
checking whether compiler accepts -std=c99... yes
checking whether compiler accepts -nostdinc... yes
checking whether compiler accepts -ffreestanding... yes
checking whether compiler accepts -fexcess-precision=standard... no
checking whether compiler accepts -frounding-math... no
checking whether compiler needs attribute((may_alias)) suppression... no
checking whether compiler accepts -Wa,--noexecstack... yes
checking whether compiler accepts -fno-stack-protector... yes
checking whether compiler accepts -fno-tree-loop-distribute-patterns... no
checking whether we should preprocess assembly to add debugging information... no
checking for optimization settings... using defaults
checking whether compiler accepts -Os... yes
components to be optimized for speed: internal malloc string
checking whether compiler accepts -pipe... yes
checking whether compiler accepts -fomit-frame-pointer... yes
checking whether compiler accepts -fno-unwind-tables... yes
checking whether compiler accepts -fno-asynchronous-unwind-tables... yes
checking whether compiler accepts -ffunction-sections... yes
checking whether compiler accepts -fdata-sections... yes
checking whether compiler accepts -Werror=implicit-function-declaration... yes
checking whether compiler accepts -Werror=implicit-int... yes
checking whether compiler accepts -Werror=pointer-sign... yes
checking whether compiler accepts -Werror=pointer-arith... yes
checking whether compiler accepts -Qunused-arguments... yes
checking preprocessor condition __PIC__... true
checking whether linker accepts -Wl,--sort-section,alignment... no
checking whether linker accepts -Wl,--sort-common... no
checking whether linker accepts -Wl,--gc-sections... no
checking whether linker accepts -Wl,--hash-style=both... no
checking whether linker accepts -Wl,--no-undefined... no
checking whether linker accepts -Wl,--exclude-libs=ALL... no
checking whether linker accepts -Wl,--dynamic-list=./dynamic.list... no
checking whether linker accepts -lgcc... no
checking whether linker accepts -lcompiler_rt... no
checking whether linker accepts /zopt/conda3/conda-bld/wasm32-libc_1534032953302/_build_env/lib/clang/6.0.1/lib/darwin15.6.0/libclang_rt.builtins-x86_64.a... no
checking whether linker accepts libpcc.a... no
using compiler runtime libraries: 
checking preprocessor condition __ILP32__... false
checking whether compiler's long double definition matches float.h... yes
checking preprocessor condition __FAST_MATH__... false
creating config.mak... done
mkdir -p lib
mkdir -p obj
mkdir -p obj/crt
mkdir -p obj/crt/x86_64
mkdir -p obj/include
mkdir -p obj/include/bits
mkdir -p obj/ldso
mkdir -p obj/src/aio
mkdir -p obj/src/complex
mkdir -p obj/src/conf
mkdir -p obj/src/crypt
mkdir -p obj/src/ctype
mkdir -p obj/src/dirent
mkdir -p obj/src/env
mkdir -p obj/src/errno
mkdir -p obj/src/exit
mkdir -p obj/src/fcntl
mkdir -p obj/src/fenv
mkdir -p obj/src/fenv/x86_64
mkdir -p obj/src/internal
mkdir -p obj/src/internal/x86_64
mkdir -p obj/src/ipc
mkdir -p obj/src/ldso
mkdir -p obj/src/ldso/x86_64
mkdir -p obj/src/legacy
mkdir -p obj/src/linux
mkdir -p obj/src/locale
mkdir -p obj/src/malloc
mkdir -p obj/src/math
mkdir -p obj/src/math/x86_64
mkdir -p obj/src/misc
mkdir -p obj/src/mman
mkdir -p obj/src/mq
mkdir -p obj/src/multibyte
mkdir -p obj/src/network
mkdir -p obj/src/passwd
mkdir -p obj/src/prng
mkdir -p obj/src/process
mkdir -p obj/src/process/x86_64
mkdir -p obj/src/regex
mkdir -p obj/src/sched
mkdir -p obj/src/search
mkdir -p obj/src/select
mkdir -p obj/src/setjmp/x86_64
mkdir -p obj/src/signal
mkdir -p obj/src/signal/x86_64
mkdir -p obj/src/stat
mkdir -p obj/src/stdio
mkdir -p obj/src/stdlib
mkdir -p obj/src/string
mkdir -p obj/src/string/x86_64
mkdir -p obj/src/temp
mkdir -p obj/src/termios
mkdir -p obj/src/thread
mkdir -p obj/src/thread/x86_64
mkdir -p obj/src/time
mkdir -p obj/src/unistd
printf '#define VERSION "%s"\n' "$(cd .; sh tools/version.sh)" > obj/src/internal/version.h
/zopt/conda3/conda-bld/wasm32-libc_1534032953302/_build_env/bin/clang -std=c99 -nostdinc -ffreestanding -Wa,--noexecstack -D_XOPEN_SOURCE=700 -I./arch/x86_64 -I./arch/generic -Iobj/src/internal -I./src/internal -Iobj/include -I./include  -Os -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith -Qunused-arguments  -c -o obj/src/internal/x86_64/syscall.o src/internal/x86_64/syscall.s
/zopt/conda3/conda-bld/wasm32-libc_1534032953302/_build_env/bin/clang -std=c99 -nostdinc -ffreestanding -Wa,--noexecstack -D_XOPEN_SOURCE=700 -I./arch/x86_64 -I./arch/generic -Iobj/src/internal -I./src/internal -Iobj/include -I./include  -Os -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith -Qunused-arguments  -c -o obj/src/ldso/x86_64/dlsym.o src/ldso/x86_64/dlsym.s
/zopt/conda3/conda-bld/wasm32-libc_1534032953302/_build_env/bin/clang -std=c99 -nostdinc -ffreestanding -Wa,--noexecstack -D_XOPEN_SOURCE=700 -I./arch/x86_64 -I./arch/generic -Iobj/src/internal -I./src/internal -Iobj/include -I./include  -Os -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith -Qunused-arguments  -c -o obj/src/ldso/x86_64/tlsdesc.o src/ldso/x86_64/tlsdesc.s
src/internal/x86_64/syscall.s:2:1: error: unknown directive
.hidden __syscall
^
src/internal/x86_64/syscall.s:3:1: error: unknown directive
.type __syscall,@function
^
src/ldso/x86_64/dlsym.s:3:1: error: unknown directive
.hidden __dlsym
^
src/ldso/x86_64/dlsym.s:4:1: error: unknown directive
.type dlsym,@function
^
src/ldso/x86_64/tlsdesc.s:3:1: error: unknown directive
.hidden __tlsdesc_static
^
src/ldso/x86_64/tlsdesc.s:4:1: error: unknown directive
.type __tlsdesc_static,@function
^
src/ldso/x86_64/tlsdesc.s:9:1: error: unknown directive
.hidden __tls_get_new
^
src/ldso/x86_64/tlsdesc.s:12:1: error: unknown directive
.hidden __tlsdesc_dynamic
^
src/ldso/x86_64/tlsdesc.s:13:1: error: unknown directive
.type __tlsdesc_dynamic,@function
^
make: *** [obj/src/ldso/x86_64/tlsdesc.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/src/ldso/x86_64/dlsym.o] Error 1
make: *** [obj/src/internal/x86_64/syscall.o] Error 1
Traceback (most recent call last):
  File "/zopt/conda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/build.py", line 2184, in build_tree
    notest=notest,
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/build.py", line 1416, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/zopt/conda3/conda-bld/wasm32-libc_1534032953302/work/conda_build.sh']' returned non-zero exit status 2.
```

</details>

<br>

<details>
<summary>Build Recipe:</summary>

```yaml
{% set version = "0.0.1a1" %}

package:
  name: wasm32-libc
  version: {{ version }}

source:
  git_url: https://github.com/jfbastien/musl.git
  git_rev: edeb5004e6e016e326c475ce53199755d76d103f

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - clangdev
    - lld
  host:

test:
  commands:
    - exit 0

about:
  home: https://github.com/jfbastien/musl
  license: MIT
  license_file: COPYRIGHT
  summary: musl libc experiment

extra:
  recipe-maintainers:
    - jakirkham
```

```bash
#!/usr/bin/env bash

unset ARCH
unset OSX_ARCH
unset CFLAGS
unset CXXFLAGS
unset LDFLAGS

export CC="${BUILD_PREFIX}/bin/clang"
export LD="${BUILD_PREFIX}/bin/lld"

./configure --prefix="${PREFIX}"  \
            --build="${BUILD}"    \
            --host="${HOST}"      \
            || { cat config.log; exit 1; }
make -j${CPU_COUNT} ${VERBOSE_AT}
make install
```

</details>

<br>

<details>
<summary>Build Tool Info:</summary>

```
$ conda info

     active environment : nanshenv3
    active env location : /zopt/conda3/envs/nanshenv3
            shell level : 1
       user config file : /Users/kirkhamj/.condarc
 populated config files : /Users/kirkhamj/.condarc
          conda version : 4.5.8
    conda-build version : 3.11.0
         python version : 3.6.5.final.0
       base environment : /zopt/conda3  (writable)
           channel URLs : https://conda.anaconda.org/nanshe/osx-64
                          https://conda.anaconda.org/nanshe/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /zopt/conda3/pkgs
                          /Users/kirkhamj/.conda/pkgs
       envs directories : /zopt/conda3/envs
                          /Users/kirkhamj/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.8 requests/2.19.1 CPython/3.6.5 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 208494839:1899195968
             netrc file : /Users/kirkhamj/.netrc
           offline mode : False
```

</details>

**Comment by jfbastien** [comment]
@sbc100 probably knows what's up.

**Comment by sbc100** [comment]
It looks like its trying to compile `src/internal/x86_64/syscall.s`.   Clearly this file should not be included in the wasm build.

Did this recipe use to work in the past?

**Comment by jakirkham** [comment]
That sounds right. There are also a few things its picking up from `src/ldso/x86_64`, which I'm guessing should be ignored as well, right?

This is my first time trying. Would not be surprised if there are things I should be doing differently as well.

Though the build script is pretty vanilla (i.e. `./configure`, `make`, `make install`). Is there anything that sticks out to you? Flags or environment variables that need to be set a particular way?

**Comment by sbc100** [comment]
We don't use `configure` and `make` to build on our waterfall since we need to support windows and mac as well as linux.

Having said that I do remember making the wasm build work with "./configure" in linux, so it *should* work.
